Code9Developers/Back-End

- .idea/workspace.xml
- README.md
- app.js
- package.json
- routes/index.js
- test/index.test.js
Added simple test for data send to login page
> Added routes testing for / and 404 page not found.

- .idea/workspace.xml
- package.json
- routes/index.js
- views/project_creation.ejs
- views/project_view.ejs
Files Updated: project_creation.ejs,custom.js
Files Added: code9Custom.js
> Added AJAX code

- .idea/workspace.xml
- package.json
- routes/index.js
- views/admin.ejs
- views/login.ejs
- views/project_creation.ejs
- views/project_view.ejs
Updated .ejs pages
Added client-sessions to package.json
> Added project view page

- .idea/workspace.xml
- public/vendors/Code-9/views/project_creation.js
> Add project_creation file

- .idea/workspace.xml
- database/test_data.js
- public/vendors/Code-9/views/admin.js
- public/vendors/Code-9/views/milestones.js
- public/vendors/Code-9/views/project_view.js
- routes/index.js
- views/project_milestones.ejs
- views/project_view.ejs
- views/top_nav.ejs
- Fix Tasks
- Added jQuery to remove and added data on those pages
> - Fix Milestone page

- .idea/workspace.xml
- public/vendors/Code-9/js/code9.js
- public/vendors/Code-9/views/project_creation.js
- public/vendors/Code-9/views/project_view.js
- public/vendors/Code-9/views/projects.js
- views/calendar.ejs
- views/error500.ejs
- views/project_creation.ejs
- views/project_edit.ejs
- views/project_milestones.ejs
- views/project_view.ejs
- views/projects.ejs
Completed the re-indexing and did some tweaks on the js files to fix the dynamically added content.
> Finished off the view files

- .idea/misc.xml
- .idea/watcherTasks.xml
- .idea/workspace.xml
- package-lock.json
- package.json
- public/vendors/Code-9/views/project_view.js
- public/vendors/Code-9/views/projects.js
- routes/index.js
- views/project_creation.ejs
Completed smtp server. Make sure your javascript version is set to ECMAScript 6 and you installed npm install nodemailer --save (check package.json)
> SMTP Server

- .idea/workspace.xml
- database/connect.js
- public/vendors/Code-9/views/projEdit.js
- public/vendors/Code-9/views/project_view.js
- public/vendors/Code-9/views/projects.js
- routes/index.js
- views/project_creation.ejs
- views/project_view.ejs
Tasks work
Milestones work
Employees assigned to projects
Project contains employee ID(Works but can be better implemented)
BUG:
Still working on project edit page to remove employee( So far you can select employees to remove and it will send a request to remove employees--Route is up to remove employees--Just need to make DB call to take employees out, call algorithm to assign new employees )
> Fixed all display on projects view page.

- .idea/workspace.xml
- database/dbs.js
- public/vendors/Code-9/views/calendar.js
- public/vendors/Code-9/views/project_view.js
- routes/index.js
- views/project_creation.ejs
- views/project_view.ejs
- views/sidebar.ejs
Just need to create test employees using the route
> Now all pages work fine.

- package-lock.json
- public/javascripts/custom.js
- views/index_dashboard.ejs
Check from line 1810 for CallError functions. Then check dashboard for the button call at the bottom of the page. Also added the library for Notifications  (pnotify)
> Edited Custom.js 

- README.md
- views/admin.ejs
- views/director_dashboard.ejs
- views/index_dashboard.ejs
- Roles updated on dropdown
- Positions updated on dropdown
> Updated Admin Page

- bin/www
- routes/admin/register-employee-post.js
- routes/email_functions.js
- Removed a header from www
- Added modular email function to test
- Created emailfunctions.js for all emails we will send
> Modular Email Functions - Start

- database/Resource-Alocation-Algorithm.js
- database/dbs.js
- database/schemas.js
- public/vendors/Code-9/views/project_creation.js
- public/vendors/Code-9/views/projects.js
- routes/admin/register-employee-post.js
- routes/all-page-components/tasks.js
- routes/projects/display-all-projects-get.js
- routes/projects/project-creation-post.js
- views/project_creation.ejs
- views/project_review.ejs
Now projects can be created
Only problem is when it stores the employee ids in the current projects, it saves the entire object rather than the id and skill.
Still to fix for director functionality:
1. Add status pending in projects page
2. Must add director login roles
3. Display information stored about approval on employee swap page
4. If conformed, replace each employee selected for removal with replacement(need db function to removed and employee based on id(must remove reference to project after removed) and will use assign project function to store employee and link to project)
5. Delete record after conformed or denied.
6. email director for approval.
> System is mostly working

- public/vendors/Code-9/views/projEdit.js
- routes/director_functionality/replacement_functionality.js
- routes/projects/project-creation-post.js
- routes/projects/project-edit.js
- views/project_edit.ejs
Look at line 141 in /routes/projects/project-creation-post.js
> Added approval process to project edit page

- routes/email_functions.js
- routes/projects/project-creation-post.js
- views/project_review.ejs
1. Can send emails to newly made person
2. Can send emails to employess assigned to a project
3. TODO Director emails
> Add Email Functions

- routes/email_functions.js
- routes/projects/project-creation-post.js
- All email functions are created. **Need to test Director email when we have data**
- PLEASE TEST ALL EMAILS FOR BUGS
> Email modularisation complete  

- app.js
- database/test_data.js
- public/vendors/Code-9/views/display_all_approvals.js
- public/vendors/Code-9/views/employee_swap.js
- public/vendors/Code-9/views/project_creation.js
- routes/admin/register-employee-post.js
- routes/director_functionality/display-approvals.js
- routes/director_functionality/replacement_functionality.js
- routes/projects/project-creation-post.js
- views/display_all_approvals.ejs
Need @JacquesSmulders  to make a function that allows you to add a skill object (e.g.{name:"skill_name",rating:4,counter:1}) when assign employees is called (either edit assign employees to to that or make a new function)
The whole approval process works but not it only assigns the new/replacement employees ids and not the skill(It should do both)
> Project review works, only one bug to sort out 

- routes/index.js
- views/training.ejs
> Added training page

- app.js
- database/Particle.js
- database/dbs.js
- database/employee-evaluations.js
- public/vendors/Code-9/views/project_creation.js
- public/vendors/Code-9/views/project_review.js
- public/vendors/Code-9/views/training.js
- routes/projects/project-creation-post.js
- routes/projects/project-review.js
- routes/projects/projects-routing.js
- views/project_creation.ejs
- views/project_review.ejs
- views/sidebar.ejs
- views/training.ejs
Can create project with new data table
Fixed  project review to display correct information with new skill object
bug fix:Fixed store employee button so projected is created when create project button is clicked (integrated store employee) @Def118 
To do: Just double check that ratings and counters for project review are working properly
> Fixed project creation with new table

- routes/admin/register-employee-post.js
Fixed employee registration to work with new skills
> bug fix:fixed register employee

- public/vendors/Code-9/js/graphs.js
- routes/admin/training.js
- routes/email_functions.js
- views/training.ejs
Added the last trainer function. Just need to test it with real data to see formatting and if it calls
> Last email function
